tasks:
  - before:  |
      nvm install 14.17.6
      nvm use 14.17.6
      nvm alias default 14.17.6
      npm config set '@atila:registry' https://node.bit.dev
    init: npm install
    command: npm start

ports:
  - port: 3000
    onOpen: open-preview
