module.exports = {
  // ... existing config ...
  resolve: {
    // ... existing resolve config ...
    alias: {
      // ... existing aliases ...
      'react/jsx-runtime': require.resolve('react/jsx-runtime'),
      'react/jsx-dev-runtime': require.resolve('react/jsx-dev-runtime')
    }
  }
  // ... rest of config ...
} 