version: 2.0
# https://medium.com/@mannycodes/deploy-react-to-firebase-with-circleci-b8f16c17a28c
jobs:
  build:
    working_directory: ~/repository
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
      - run:
          name: Configure @atila as a Scoped Registry
          command: npm config set '@atila:registry' https://node.bit.dev
      - run:
          name: install-npm-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
  deploy: # deploy script
    resource_class: large
    working_directory: ~/repository
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - run:
          name: Configure @atila as a Scoped Registry
          command: npm config set '@atila:registry' https://node.bit.dev
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
      - run:
          name: install-npm-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # build react
          name: react-build
          command: export NODE_OPTIONS=--max_old_space_size=4096 ; npm run build
      - run: # todo change -P to default, to deploy to prod on master branch
          name: Deploy Netlify Prod
          filters:
            branches:
              only: master
          command: ./node_modules/.bin/netlify deploy --dir=./build --prod --site $NETLIFY_SITE_ID_PROD -m "${CIRCLE_BRANCH} ${CIRCLE_SHA1} ${CIRCLE_PULL_REQUEST}"
      - run: # todo change -P to default, to deploy to prod on master branch
          name: Deploy Netlify Demo
          filters:
            branches:
              only: demo
          command: ./node_modules/.bin/netlify deploy --dir=./build --prod --site $NETLIFY_SITE_ID_DEMO -m "${CIRCLE_BRANCH} ${CIRCLE_SHA1} ${CIRCLE_PULL_REQUEST}"
      - run: # todo change -P to default, to deploy to prod on master branch
          name: Deploy Netlify Staging
          filters:
            branches:
              ignore: 
               - master
               - demo
          command: ./node_modules/.bin/netlify deploy --dir=./build --prod --site $NETLIFY_SITE_ID_STAGING -m "${CIRCLE_BRANCH} ${CIRCLE_SHA1} ${CIRCLE_PULL_REQUEST}"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build # perform this first
      - deploy: # perform second
          requires:
            - build