import React from 'react'
import { connect } from 'react-redux';
import { Application } from '../../../models/Application.class'
import { Scholarship, ScholarshipQuestion } from '../../../models/Scholarship.class'
import { UserProfile } from '../../../models/UserProfile.class';
import { joinListGrammatically, prettifyKeys, stripHtml } from '../../../services/utils';

export interface ApplicationDetailViewProps {
    scholarship: Scholarship,
    application: Application,
    userProfileLoggedIn: UserProfile,
    questions: ScholarshipQuestion[],
    responses: any;
}

/**
 * questions is a list in one of two formats:
    * [{key: "", question: ""}]
    * [{key: ""}]
    *
    * scholarship_responses:
    * { "favourite-sport": "<p>volleyball</p>",
    * "why-do-you-deserve-this-scholarship": "<p>I like food</p>",
    * "example-file": "https://example.com/example.pdf"}
    * user_profile_responses:
    * email: "test_user@atila.ca"
    * first_name: "FirstName"
    * last_name: "LastName"
*/


export function ApplicationResponseDisplay({question, responses, previewMode = false} :
     {question: ScholarshipQuestion, responses: any, previewMode?: boolean}) {

    let responseDisplay = responses[question.key];
    switch (question.type) {
        case 'long_answer':
        case "medium_answer":
        case "short_answer":
            if (previewMode) {
                responseDisplay =  stripHtml(responses[question.key]).substring(0, 140);
            } else {
                responseDisplay = <div className="my-1" dangerouslySetInnerHTML={{__html: responses[question.key]}}/>
            }
            
            break;
        case 'checkbox':
            responseDisplay = responses[question.key] ? "Yes" : "No"
            break;
        case 'file':
            responseDisplay = <a href={responses[question.key]} target="_blank"  rel="noopener noreferrer">
                    View File
                </a> 
            break;
        case 'multi_select':
            responseDisplay = joinListGrammatically(responses[question.key])
            break;
        default:
            break;
    }

    // added || null fallback return because it was giving an error that this function returned nothing
    // However, the cause might be something different, so we might be able to remove this.
    return responseDisplay || null
}

function ApplicationDetailView(props: ApplicationDetailViewProps) {

  const { scholarship, application, userProfileLoggedIn, questions, responses } = props;
  let isOwnerOfApplication = userProfileLoggedIn && application.user && ((application.user as UserProfile).user === userProfileLoggedIn.user);

  let displayRealName = isOwnerOfApplication || scholarship.is_winner_selected || !scholarship.is_blind_applications;

  return( <>
    {
        questions.map((question) => {
            if (question.key === "first_name" || question.key === "last_name") {
                // All applications are autogenerated with a first_name_code and last_name_code
                // that can be used for blind applications.
                const key_code = `${question.key}_code`;
      
                return (<div key={question.key}>
                    <div className="white-space-pre-wrap">
                        <b>{prettifyKeys(question.key)}:</b><br/>
                        {displayRealName? responses[question.key] : (application as any)[key_code]}
                    </div>
                </div>);
            }
            if (question.key === "email" && !isOwnerOfApplication) {
                return <></>;
            }
            return (<div key={question.key}>
                <div className="white-space-pre-wrap">
                    <b>{question.question || prettifyKeys(question.key)}:</b><br/>
                    <ApplicationResponseDisplay question={question} responses={responses} />
                </div>
            </div>)})
    }
  </>);
}

const mapStateToProps = (state: any) => {
    return { userProfileLoggedIn: state.data.user.loggedInUserProfile };
};

export default connect(mapStateToProps)(ApplicationDetailView);