
<table border="1">
    <tbody>
    <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
        <td>6</td>
    </tr>
    <tr>
        <td>this</td>
        <td>sample</td>
        <td>sample</td>
        <td>sample</td>
        <td>sample</td>
        <td>sample</td>
    </tr>
    <tr>
        <td>is</td>
        <td>sample</td>
        <td>sample</td>
        <td>sample</td>
        <td>samplesample</td>
        <td>sample</td>
    </tr>
    <tr>
        <td>the&nbsp;</td>
        <td>samplesample</td>
        <td>sample</td>
        <td>sample</td>
        <td>sample</td>
        <td>sample</td>
    </tr>
    <tr>
        <td>rubric</td>
        <td>sample</td>
        <td>sample</td>
        <td>sample</td>
        <td>sample</td>
        <td>samplesample</td>
    </tr>
    </tbody>
</table>
<p></p>