export const POINTS_FOR_CREATING_AN_ACCOUNT = 20;
export const POINTS_FOR_SUBMITTING_AN_APPLICATION = 100;
export const POINTS_FOR_BEING_A_SCHOLARSHIP_FINALIST = 300;
export const POINTS_FOR_BEING_A_SCHOLARSHIP_WINNER = 500;
export const POINTS_FOR_STARTING_A_SCHOLARSHIP = 1000;
export const POINTS_FOR_CONTRIBUTING_TO_A_SCHOLARSHIP = 800;
export const ADDITIONAL_POINTS_PER_100_DOLLARS_CREATE_SCHOLARSHIP = 10;
export const ADDITIONAL_POINTS_PER_100_DOLLARS_CONTRIBUTE_SCHOLARSHIP = 5;
