// If you make any changes here, notify in the Github repo and update backend as well
// https://github.com/ademidun/atila-django/blob/master/helpers/constants.py

export const MAJORS_LIST = [
    'Accounting',
    'African Studies',
    'Agriculture',
    'Agro-Environmental Sciences',
    'Anatomy',
    'Animal Biology',
    'Animal Health',
    'Animal Production',
    'Anthropology',
    'Applied Ecology',
    'Applied Mathematics',
    'Arabic Language',
    'Architecture',
    'Art History',
    'Behavioural Science',
    'Biochemistry',
    'Biodiversity',
    'Bioengineering',
    'Biology',
    'Biomedical Engineering',
    'Bioresource Engineering',
    'Biotechnology',
    'Business',
    'Canadian Ethnic',
    'Canadian Studies',
    'Catholic Studies',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Classics',
    'Cognitive Science',
    'Communication Studies',
    'Composition',
    'Computer Engineering',
    'Computer Science',
    'Construction Engineering',
    'Criminology',
    'Dentistry',
    'Dietetics',
    'Earth',
    'Earth Sciences',
    'Earth System Science',
    'East Asian Cultural Studies',
    'East Asian Language',
    'East Asian Studies',
    'Ecology',
    'Economics',
    'Education',
    'Educational Psychology',
    'Electrical Engineering',
    'Engineering',
    'English',
    'Entrepreneurship',
    'Environment',
    'European Literature',
    'Farm Management',
    'Field Studies',
    'Film',
    'Finance',
    'Food Production',
    'Food Science',
    'Food Science & Nutritional Science',
    'Gender, Sexuality, Feminist, and Social Justice Studies',
    'General Science',
    'Geochemistry',
    'Geographic Information Systems',
    'Geography',
    'Geography: Urban Systems',
    'Geology',
    'German Language',
    'German Studies',
    'German Studies: Literature',
    'Global Food Security',
    'Health Geography',
    'Health Sciences',
    'Hispanic Studies',
    'History',
    'History and Philosophy of Science',
    'Human Nutrition',
    'Immunology',
    'Indigenous Studies',
    'Industrial Relations',
    'Information Systems',
    'International Development Studies',
    'International Management',
    'Investment Management',
    'Italian Studies',
    'Jewish Studies',
    'Kinesiology',
    'Labour-Management Relations and Human Resources',
    'Law',
    'Liberal Arts',
    'Life Sciences',
    'Linguistics',
    'MBA',
    'Management',
    'Managing for Sustainability',
    'Marketing',
    'Materials Engineering',
    'Mathematics',
    'Mechanical Engineering',
    'Mechatronics Engineering',
    'Medical Sciences',
    'Medicine',
    'Medieval Studies',
    'Meteorology',
    'Microbiology',
    'Mining Engineering',
    'Music',
    'Nanotechnology',
    'Natural History',
    'Neuroscience',
    'North American Studies',
    'Nursing',
    'Nutrition',
    'Occupational Therapy',
    'Operations Management',
    'Organizational Behaviour',
    'Persian Language',
    'Pharmacology',
    'Philosophy',
    'Physical Therapy',
    'Physics',
    'Physiology',
    'Planetary Sciences',
    'Plant Biology',
    'Plant Production',
    'Political Science',
    'Professional Agrology',
    'Psychology',
    'Quebec Studies',
    'Religion',
    'Religious Studies',
    'Russian',
    'Social Science',
    'Social Studies of Medicine',
    'Social Work',
    'Sociology',
    'Software Engineering',
    'Statistics',
    'Teacher\'s College',
    'Teaching English as a Second Language',
    'Technological Entrepreneurship',
    'Turkish Language',
    'Urdu Language',
    'Veterinary Studies',
    'Veterinary Studies',
    'Visual Arts',
    'Wildlife Biology',
    'World Islamic & Middle East Studies',
    'World Religions'
];

export const SCHOOLS_LIST = [
    'Acadia University',
    'Algoma University',
    'Algonquin College',
    'Ashton College',
    'Assumption University',
    'Athabasca University',
    'Augustana University College',
    'Bishop\'s University',
    'Bow Valley College',
    'Brandon University',
    'Brescia College',
    'British Columbia Institute of Technology',
    'British Columbia Open University',
    'Brock University',
    'Camosun College',
    'Campion College',
    'Canadian College of Business & Computers',
    'Canadian Mennonite University',
    'Capilano College',
    'Carleton University',
    'Centennial College',
    'College of New Caledonia',
    'College of the Rockies',
    'Collège Boréal',
    'Columbia College',
    'Concordia University',
    'Concordia University College of Alberta',
    'Conestoga College',
    'Dalhousie University',
    'DeGroote School of Business',
    'DeGroote School of Medicine',
    'DeVry Institute of Technology',
    'Desautels Faculty of Management',
    'Dominican College of Philosophy and Theology',
    'Douglas College',
    'Durham College',
    'Emily Carr Institute of Art + Design',
    'Fanshawe College',
    'First Nations University of Canada',
    'George Brown College',
    'Humber College',
    'Huron University College',
    'Institut Armand-Frappier, Université du Québec',
    'Institut National de la Recherche Scientifique, Université du Québec',
    'Ivey Business School',
    'King\'s College',
    'King\'s University College',
    'Kingston College',
    'Kwantleen University College',
    'Lakehead University',
    'Langara College',
    'Lansbridge University',
    'Laurentian University of Sudbury',
    'Luther College',
    'MacEwan University',
    'Malaspina University College',
    'McGill University',
    'McMaster University',
    'Memorial University of Newfoundland',
    'Mount Allison University',
    'Mount Royal College',
    'Mount Saint Vincent University',
    'Nicola Valley Institute of Technology',
    'Nipissing University',
    'North Island College',
    'Northern Alberta Institute of Technology',
    'Northern Lights College',
    'Nova Scotia Agricultural College',
    'Nova Scotia College of Art and Design',
    'Okanagan University College',
    'Ontario College of Art and Design',
    'Osgoode Law School',
    'Pacific International College',
    'Queen\'s University',
    'Quest University',
    'Redeemer College',
    'Regent College',
    'Rotman Commerce',
    'Royal Military College of Canada',
    'Royal Roads University',
    'Ryerson Polytechnic University',
    'Saskatchewan Indian Federated College',
    'Sauder School of Business',
    'Sauder School of Business',
    'Schulich School of Business',
    'Schulich School of Medicine & Dentistry',
    'Selkirk College',
    'Seneca College',
    'Sheridan College',
    'Simon Fraser University',
    'Smith School of Business',
    'Southern Alberta Institute of Technology',
    'St. Anne University',
    'St. Clair College',
    'St. Francis Xavier University',
    'St. Mary\'s University',
    'St. Paul University',
    'St. Thomas University',
    'Thompson Rivers University',
    'Trent University',
    'Trinity Western University',
    'Télé-université, Université du Québec',
    'University Canada West',
    'University College of Cape Breton',
    'University College of Saint-Boniface',
    'University College of the Cariboo',
    'University College of the Fraser Valley',
    'University of Alberta',
    'University of British Columbia',
    'University of Calgary',
    'University of Guelph',
    'University of King\'s College',
    'University of Lethbridge',
    'University of Manitoba',
    'University of Moncton',
    'University of Moncton, Edmundston',
    'University of Moncton, Shippagan',
    'University of New Brunswick',
    'University of New Brunswick, Saint John',
    'University of Northern British Columbia',
    'University of Ontario Institute of Technology',
    'University of Ottawa',
    'University of Prince Edward Island',
    'University of Québec',
    'University of Regina',
    'University of Saskatchewan',
    'University of St. Jerome\'s College',
    'University of St. Michael\'s College',
    'University of Sudbury',
    'University of Toronto',
    'University of Toronto, Mississauga',
    'University of Toronto, Scarborough',
    'University of Trinity College',
    'University of Victoria',
    'University of Waterloo',
    'University of Western Ontario',
    'University of Windsor',
    'University of Winnipeg',
    'Université Laval',
    'Université de Montréal',
    'Université de Sherbrooke',
    'Université du Québec en Abitibi-Témiscamingue',
    'Université du Québec en Outaouais',
    'Université du Québec à Chicoutimi',
    'Université du Québec à Montréal',
    'Université du Québec à Rimouski',
    'Université du Québec à Trois-Rivières',
    'Vancouver Community College',
    'Victoria University Toronto, University of Toronto',
    'Wilfrid Laurier University',
    'William and Catherine Booth College',
    'York University',
    'Yukon College',
    'École Polytechnique de Montréal, Université de Montréal',
    'École de technologie supérieure, Université du Québec',
    'École des Hautes Études Commerciales',
    'École nationale d\'administration publique, Université du Québec'
];
export const ETHNICITIES = [
    'Aboriginal/First Nations',
    'Asian/East-Asian',
    'Black/African-American',
    'Indian/South-Asian',
    'Latino/Hispanic',
    'Middle Eastern',
    'Visible Minority',
    'White/Caucasian'
];
export const COUNTRIES = [
    'Afghanistan',
    'Åland Islands',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antarctica',
    'Antigua & Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Ascension Island',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bosnia & Herzegovina',
    'Botswana',
    'Brazil',
    'British Indian Ocean Territory',
    'British Virgin Islands',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Canary Islands',
    'Cape Verde',
    'Caribbean Netherlands',
    'Cayman Islands',
    'Central African Republic',
    'Ceuta & Melilla',
    'Chad',
    'Chile',
    'China',
    'Christmas Island',
    'Cocos (Keeling) Islands',
    'Colombia',
    'Comoros',
    'Congo - Brazzaville',
    'Congo - Kinshasa',
    'Cook Islands',
    'Costa Rica',
    'Côte d’Ivoire',
    'Croatia',
    'Cuba',
    'Curaçao',
    'Cyprus',
    'Czechia',
    'Denmark',
    'Diego Garcia',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Eurozone',
    'Falkland Islands',
    'Faroe Islands',
    'Fiji',
    'Finland',
    'France',
    'French Guiana',
    'French Polynesia',
    'French Southern Territories',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hong Kong SAR China',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jersey',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macau SAR China',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar (Burma)',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Norfolk Island',
    'North Korea',
    'Northern Mariana Islands',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestinian Territories',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Pitcairn Islands',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Réunion',
    'Romania',
    'Russia',
    'Rwanda',
    'Samoa',
    'San Marino',
    'São Tomé & Príncipe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Georgia & South Sandwich Islands',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'St. Barthélemy',
    'St. Helena',
    'St. Kitts & Nevis',
    'St. Lucia',
    'St. Martin',
    'St. Pierre & Miquelon',
    'St. Vincent & Grenadines',
    'Sudan',
    'Suriname',
    'Svalbard & Jan Mayen',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad & Tobago',
    'Tristan da Cunha',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks & Caicos Islands',
    'Tuvalu',
    'U.S. Outlying Islands',
    'U.S. Virgin Islands',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United Nations',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Wallis & Futuna',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe'
];
export const LANGUAGES = [
    'Agnostic',
    'Atheist',
    'Buddhism',
    'Christianity',
    'Hinduism',
    'Islam',
    'Judaism',
    'Sikhism'

];
export const RELIGIONS = [
    'Agnostic',
    'Atheist',
    'Buddhism',
    'Christianity',
    'Hinduism',
    'Islam',
    'Judaism',
    'Sikhism'

];
export const ACTIVITIES = [
    // "3D Printing", // commented out 3d printing so it doens't show up in master list before accounting and acadia university
    'Acting',
    'Action Figure',
    'Aircraft Spotting',
    'Amateur Astronomy',
    'Amateur Radio',
    'Animal Fancy',
    'Antiquing',
    'Antiquities',
    'Art Collecting',
    'Astrology',
    'Astronomy',
    'Aviation',
    'Backpacking (Travel)',
    'Baking',
    'Base Jumping',
    'Baton Twirling',
    'Beekeeping',
    'Bird Watching',
    'Blacksmithing',
    'Board Game',
    'Board Sports',
    'Book Collecting',
    'Book Restoration',
    'Bowling',
    'Brazilian Jiu-Jitsu',
    'Breakdancing',
    'Bus Spotting',
    'Cabaret',
    'Calligraphy',
    'Camping',
    'Candle Making',
    'Canyoning',
    'Card Collecting',
    'Cheerleading',
    'Climbing',
    'Coin Collecting',
    'Color Guard (Flag Spinning)',
    'Coloring Book',
    'Comic Book Collecting',
    'Competitive Dance',
    'Computer Programming',
    'Contract Bridge',
    'Cooking',
    'Cosplaying',
    'Couponing',
    'Creative Writing',
    'Crocheting',
    'Cross-Stitch',
    'Crossword Puzzles',
    'Cryptography',
    'Cue Sports',
    'Dance',
    'Debate',
    'Deltiology',
    'Die-Cast Toy',
    'Digital Art',
    'Disc Golf',
    'Dog Sport',
    'Dowsing',
    'Drama',
    'Drawing',
    'Driving',
    'Electronics',
    'Element Collecting',
    'Embroidery',
    'Equestrianism',
    'Exhibition Drill',
    'Fantasy Sport',
    'Fashion',
    'Film Memorabilia',
    'Fishkeeping',
    'Flag Football',
    'Flower Arranging',
    'Footbag',
    'Foraging',
    'Fossil Hunting',
    'Freestyle Football',
    'Gardening',
    'Genealogy',
    'Geocaching',
    'Ghost Hunting',
    'Glassblowing',
    'Go (Game)',
    'Graffiti',
    'Gunsmithing',
    'Handball',
    'Herpetoculture',
    'Herping',
    'High-Power Rocketry',
    'Hiking',
    'Homebrewing',
    'Hooping',
    'Horseback Riding',
    'Hunting',
    'Hydroponics',
    'Inline Skating',
    'Insect Collecting',
    'Jewelry Making',
    'Jigsaw Puzzles',
    'Jogging',
    'Juggling',
    'Kart Racing',
    'Kayaking',
    'Kite',
    'Kitesurfing',
    'Knife Making',
    'Knife Throwing',
    'Knitting',
    'Kombucha',
    'Lace',
    'Lapidary Club',
    'Larping',
    'Laser Tag',
    'Leather Crafting',
    'Lego',
    'Letterboxing (Hobby)',
    'Machining',
    'Magic (Illusion)',
    'Magnet Fishing',
    'Mahjong',
    'Marbles',
    'Marching Band',
    'Martial Arts',
    'Metal Detecting',
    'Metal Detector',
    'Metalworking',
    'Meteorology',
    'Microscopy',
    'Mineral Collecting',
    'Model Aircraft',
    'Model Building',
    'Motor Sports',
    'Mountain Biking',
    'Movies',
    'Mushroom Hunting',
    'Music',
    'Mycology',
    'Nordic Skating',
    'Origami',
    'Paintball',
    'Painting',
    'Pet',
    'Philately',
    'Photography',
    'Poi (Performance Art)',
    'Poker',
    'Pottery',
    'Pressed Flower Craft',
    'Puzzle',
    'Quilling',
    'Quilting',
    'Radio-Controlled Car',
    'Rappelling',
    'Reading (Process)',
    'Record Collecting',
    'Road Cycling',
    'Robotics',
    'Rock Balancing',
    'Rock Climbing',
    'Role-Playing Game',
    'Roller Skating',
    'Rowing (Sport)',
    'Rugby Football',
    'Running',
    'Sand Art And Play',
    'Satellite Watching',
    'Scouting',
    'Scrapbooking',
    'Scuba Diving',
    'Sculling',
    'Sculpting',
    'Sea Glass',
    'Seashell',
    'Second-Language Acquisition',
    'Sewing',
    'Shooting Sport',
    'Shopping',
    'Shortwave Listening',
    'Singing',
    'Sketch (Drawing)',
    'Skimboarding',
    'Skydiving',
    'Slacklining',
    'Slot Car Racing',
    'Soapmaking',
    'Speedcubing',
    'Sport Stacking',
    'Squash (Sport)',
    'Stamp Collecting',
    'Stand-Up Comedy',
    'Stone Collecting',
    'Stone Skipping',
    'Sun Bathing',
    'Table Football',
    'Tabletop Game',
    'Tai Chi',
    'Taxidermy',
    'Television Program',
    'Tennis Polo',
    'Topiary',
    'Tour Skating',
    'Trainspotting (Hobby)',
    'Travel',
    'Traveling',
    'Ultimate (Sport)',
    'Urban Exploration',
    'Vacation',
    'Vehicle Restoration',
    'Video Game Collecting',
    'Video Gaming',
    'Videophile',
    'Vintage Cars',
    'Walking',
    'Water Polo',
    'Water Sports',
    'Web Surfing',
    'Weight Training',
    'Whale Watching',
    'Whittling',
    'Wood Carving',
    'Woodworking',
    'Worldbuilding',
    'Writing',
    'Yo-Yoing'
];
export const SPORTS = [
    'Aikido',
    'Air Sports',
    'Airsoft',
    'Alpine',
    'Alpine Skiing',
    'American',
    'Any Sport',
    'Archery',
    'Arm Wrestling',
    'Athletics',
    'Athletics',
    'Australian Rules Football',
    'Auto Racing',
    'Badminton',
    'Bandy',
    'Baseball',
    'Basketball',
    'Beach Soccer',
    'Beach Volleyball',
    'Biathlon',
    'Biathlon',
    'Billiard Sports',
    'Bobsleigh',
    'Bocce',
    'Boccia',
    'Bodyboarding',
    'Bodybuilding',
    'Boot Throwing',
    'Bowling (Canadian Five-Pin)',
    'Bowling (Ten-Pin)',
    'Bowls',
    'Boxing',
    'Broomball',
    'Canoeing',
    'Casting',
    'Chess',
    'Cricket',
    'Croquet',
    'Cross-Country',
    'Cross-Country Skiing',
    'Curling',
    'Cycling',
    'Dancesport',
    'Darts',
    'Dragon Boat Racing',
    'Elephant Polo',
    'Equestrian',
    'Fencing',
    'Field Hockey',
    'Figure Skating',
    'Fishing',
    'Fistball',
    'Floorball',
    'Flying Disc',
    'Foosball',
    'Football',
    'Football (Gaelic)',
    'Freestyle',
    'Game Fishing',
    'Goalball',
    'Golf',
    'Greyhound Racing',
    'Gymnastics',
    'Handball (Court)',
    'Handball (Team)',
    'Harness Horse Racing',
    'Horse Racing',
    'Horseshoes',
    'Hurling',
    'Ice Hockey',
    'Ice Skating',
    'Ice Sledge Hockey',
    'Inline Hockey',
    'Intercrosse',
    'Ju-Jitsu',
    'Judo',
    'Karate',
    'Kendo',
    'Kickboxing',
    'Korfball',
    'Kung Fu',
    'Lacrosse',
    'Life Saving',
    'Luge',
    'Miniature Golf',
    'Mixed Martial Arts',
    'Modern Pentathlon',
    'Motorcycle Sport',
    'Mountain Running',
    'Mountainboarding',
    'Mountaineering',
    'Muay Thai',
    'Netball',
    'Nordic Combined',
    'Nordic Skiing',
    'Orienteering',
    'Paddleball',
    'Parkour',
    'Petanque',
    'Pigeon Racing',
    'Pitch And Putt',
    'Pole Dance',
    'Polo',
    'Powerboating',
    'Powerlifting',
    'Practical Shooting',
    'Quidditch',
    'Racquetball',
    'Rafting',
    'Ringette',
    'Rink Hockey',
    'Roller Derby',
    'Roller Sports',
    'Rope Skipping',
    'Rounders',
    'Rowing',
    'Rugby Fives',
    'Rugby League',
    'Rugby Union',
    'Sailing',
    'Shooting',
    'Skateboarding',
    'Skeleton',
    'Ski Jumping',
    'Skibobbing',
    'Skiing',
    'Sled Dog Sports',
    'Snowboarding',
    'Soccer',
    'Soft Tennis',
    'Softball',
    'Speed Skating',
    'Sports Climbing',
    'Sports Fishing',
    'Squash',
    'Sumo',
    'Surfing',
    'Swimming',
    'Swimming',
    'Table Soccer',
    'Table Tennis',
    'Taekwondo',
    'Tchoukball',
    'Tennis',
    'Throwball',
    'Touch Football',
    'Track and Field',
    'Triathlon',
    'Ultimate Frisbee',
    'Underwater Sports',
    'Volleyball',
    'Water Skiing',
    'Weightlifting',
    'Wheelchair Basketball',
    'Wheelchair Curling',
    'Wheelchair Fencing',
    'Wheelchair Rugby',
    'Wheelchair Tennis',
    'Wrestling',
    'Yoga'
];
export const DISABILITIES = [
    'Autism',
    'Chronic Illness',
    'Hearing Loss and Deafness',
    'Intellectual Disability',
    'Learning Disability',
    'Memory Loss',
    'Mental Health',
    'Physical Disability',
    'Speech and Language Disorders',
    'Vision Loss and Blindness'
];