export const MAJORS_LIST = [
    'Accounting',
    'African Studies',
    'Agriculture',
    'Agro-Environmental Sciences',
    'Anatomy',
    'Animal Biology',
    'Animal Health',
    'Animal Production',
    'Anthropology',
    'Applied Ecology',
    'Applied Mathematics',
    'Arabic Language',
    'Architecture',
    'Art History',
    'Behavioural Science',
    'Biochemistry',
    'Biodiversity',
    'Bioengineering',
    'Biology',
    'Biomedical Engineering',
    'Bioresource Engineering',
    'Biotechnology',
    'Business',
    'Canadian Ethnic',
    'Canadian Studies',
    'Catholic Studies',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Classics',
    'Cognitive Science',
    'Communication Studies',
    'Composition',
    'Computer Engineering',
    'Computer Science',
    'Construction Engineering',
    'Criminology',
    'Dentistry',
    'Dietetics',
    'Earth',
    'Earth Sciences',
    'Earth System Science',
    'East Asian Cultural Studies',
    'East Asian Language',
    'East Asian Studies',
    'Ecology',
    'Economics',
    'Education',
    'Educational Psychology',
    'Electrical Engineering',
    'Engineering',
    'English',
    'Entrepreneurship',
    'Environment',
    'European Literature',
    'Farm Management',
    'Field Studies',
    'Film',
    'Finance',
    'Food Production',
    'Food Science',
    'Food Science & Nutritional Science',
    'Gender, Sexuality, Feminist, and Social Justice Studies',
    'General Science',
    'Geochemistry',
    'Geographic Information Systems',
    'Geography',
    'Geography: Urban Systems',
    'Geology',
    'German Language',
    'German Studies',
    'German Studies: Literature',
    'Global Food Security',
    'Health Geography',
    'Health Sciences',
    'Hispanic Studies',
    'History',
    'History and Philosophy of Science',
    'Human Nutrition',
    'Immunology',
    'Indigenous Studies',
    'Industrial Relations',
    'Information Systems',
    'International Development Studies',
    'International Management',
    'Investment Management',
    'Italian Studies',
    'Jewish Studies',
    'Kinesiology',
    'Labour-Management Relations and Human Resources',
    'Law',
    'Liberal Arts',
    'Life Sciences',
    'Linguistics',
    'MBA',
    'Management',
    'Managing for Sustainability',
    'Marketing',
    'Materials Engineering',
    'Mathematics',
    'Mechanical Engineering',
    'Mechatronics Engineering',
    'Medical Sciences',
    'Medicine',
    'Medieval Studies',
    'Meteorology',
    'Microbiology',
    'Mining Engineering',
    'Music',
    'Nanotechnology',
    'Natural History',
    'Neuroscience',
    'North American Studies',
    'Nursing',
    'Nutrition',
    'Occupational Therapy',
    'Operations Management',
    'Organizational Behaviour',
    'Persian Language',
    'Pharmacology',
    'Philosophy',
    'Physical Therapy',
    'Physics',
    'Physiology',
    'Planetary Sciences',
    'Plant Biology',
    'Plant Production',
    'Political Science',
    'Professional Agrology',
    'Psychology',
    'Quebec Studies',
    'Religion',
    'Religious Studies',
    'Russian',
    'Social Science',
    'Social Studies of Medicine',
    'Social Work',
    'Sociology',
    'Software Engineering',
    'Statistics',
    'Teacher\'s College',
    'Teaching English as a Second Language',
    'Technological Entrepreneurship',
    'Turkish Language',
    'Urdu Language',
    'Veterinary Studies',
    'Veterinary Studies',
    'Visual Arts',
    'Wildlife Biology',
    'World Islamic & Middle East Studies',
    'World Religions'
];