export const MAJORS_LIST = [
    'Accounting',
    'African Studies',
    'Agriculture',
    'Agro-Environmental Sciences',
    'Anatomy',
    'Animal Biology',
    'Animal Health',
    'Animal Production',
    'Anthropology',
    'Applied Ecology',
    'Applied Mathematics',
    'Arabic Language',
    'Architecture',
    'Art History',
    'Behavioural Science',
    'Biochemistry',
    'Biodiversity',
    'Bioengineering',
    'Biology',
    'Biomedical Engineering',
    'Bioresource Engineering',
    'Biotechnology',
    'Business',
    'Canadian Ethnic',
    'Canadian Studies',
    'Catholic Studies',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Classics',
    'Cognitive Science',
    'Communication Studies',
    'Composition',
    'Computer Engineering',
    'Computer Science',
    'Construction Engineering',
    'Criminology',
    'Dentistry',
    'Dietetics',
    'Earth',
    'Earth Sciences',
    'Earth System Science',
    'East Asian Cultural Studies',
    'East Asian Language',
    'East Asian Studies',
    'Ecology',
    'Economics',
    'Education',
    'Educational Psychology',
    'Electrical Engineering',
    'Engineering',
    'English',
    'Entrepreneurship',
    'Environment',
    'European Literature',
    'Farm Management',
    'Field Studies',
    'Film',
    'Finance',
    'Food Production',
    'Food Science',
    'Food Science & Nutritional Science',
    'Gender, Sexuality, Feminist, and Social Justice Studies',
    'General Science',
    'Geochemistry',
    'Geographic Information Systems',
    'Geography',
    'Geography: Urban Systems',
    'Geology',
    'German Language',
    'German Studies',
    'German Studies: Literature',
    'Global Food Security',
    'Health Geography',
    'Health Sciences',
    'Hispanic Studies',
    'History',
    'History and Philosophy of Science',
    'Human Nutrition',
    'Immunology',
    'Indigenous Studies',
    'Industrial Relations',
    'Information Systems',
    'International Development Studies',
    'International Management',
    'Investment Management',
    'Italian Studies',
    'Jewish Studies',
    'Kinesiology',
    'Labour-Management Relations and Human Resources',
    'Law',
    'Liberal Arts',
    'Life Sciences',
    'Linguistics',
    'MBA',
    'Management',
    'Managing for Sustainability',
    'Marketing',
    'Materials Engineering',
    'Mathematics',
    'Mechanical Engineering',
    'Mechatronics Engineering',
    'Medical Sciences',
    'Medicine',
    'Medieval Studies',
    'Meteorology',
    'Microbiology',
    'Mining Engineering',
    'Music',
    'Nanotechnology',
    'Natural History',
    'Neuroscience',
    'North American Studies',
    'Nursing',
    'Nutrition',
    'Occupational Therapy',
    'Operations Management',
    'Organizational Behaviour',
    'Persian Language',
    'Pharmacology',
    'Philosophy',
    'Physical Therapy',
    'Physics',
    'Physiology',
    'Planetary Sciences',
    'Plant Biology',
    'Plant Production',
    'Political Science',
    'Professional Agrology',
    'Psychology',
    'Quebec Studies',
    'Religion',
    'Religious Studies',
    'Russian',
    'Social Science',
    'Social Studies of Medicine',
    'Social Work',
    'Sociology',
    'Software Engineering',
    'Statistics',
    'Teacher\'s College',
    'Teaching English as a Second Language',
    'Technological Entrepreneurship',
    'Turkish Language',
    'Urdu Language',
    'Veterinary Studies',
    'Veterinary Studies',
    'Visual Arts',
    'Wildlife Biology',
    'World Islamic & Middle East Studies',
    'World Religions'
];

export const SCHOOLS_LIST = [
    'Acadia University',
    'Algoma University',
    'Algonquin College',
    'Ashton College',
    'Assumption University',
    'Athabasca University',
    'Augustana University College',
    'Bishop\'s University',
    'Bow Valley College',
    'Brandon University',
    'Brescia College',
    'British Columbia Institute of Technology',
    'British Columbia Open University',
    'Brock University',
    'Camosun College',
    'Campion College',
    'Canadian College of Business & Computers',
    'Canadian Mennonite University',
    'Capilano College',
    'Carleton University',
    'Centennial College',
    'College of New Caledonia',
    'College of the Rockies',
    'Collège Boréal',
    'Columbia College',
    'Concordia University',
    'Concordia University College of Alberta',
    'Conestoga College',
    'Dalhousie University',
    'DeGroote School of Business',
    'DeGroote School of Medicine',
    'DeVry Institute of Technology',
    'Desautels Faculty of Management',
    'Dominican College of Philosophy and Theology',
    'Douglas College',
    'Durham College',
    'Emily Carr Institute of Art + Design',
    'Fanshawe College',
    'First Nations University of Canada',
    'George Brown College',
    'Humber College',
    'Huron University College',
    'Institut Armand-Frappier, Université du Québec',
    'Institut National de la Recherche Scientifique, Université du Québec',
    'Ivey Business School',
    'King\'s College',
    'King\'s University College',
    'Kingston College',
    'Kwantleen University College',
    'Lakehead University',
    'Langara College',
    'Lansbridge University',
    'Laurentian University of Sudbury',
    'Luther College',
    'MacEwan University',
    'Malaspina University College',
    'McGill University',
    'McMaster University',
    'Memorial University of Newfoundland',
    'Mount Allison University',
    'Mount Royal College',
    'Mount Saint Vincent University',
    'Nicola Valley Institute of Technology',
    'Nipissing University',
    'North Island College',
    'Northern Alberta Institute of Technology',
    'Northern Lights College',
    'Nova Scotia Agricultural College',
    'Nova Scotia College of Art and Design',
    'Okanagan University College',
    'Ontario College of Art and Design',
    'Osgoode Law School',
    'Pacific International College',
    'Queen\'s University',
    'Quest University',
    'Redeemer College',
    'Regent College',
    'Rotman Commerce',
    'Royal Military College of Canada',
    'Royal Roads University',
    'Ryerson Polytechnic University',
    'Saskatchewan Indian Federated College',
    'Sauder School of Business',
    'Sauder School of Business',
    'Schulich School of Business',
    'Schulich School of Medicine & Dentistry',
    'Selkirk College',
    'Seneca College',
    'Sheridan College',
    'Simon Fraser University',
    'Smith School of Business',
    'Southern Alberta Institute of Technology',
    'St. Anne University',
    'St. Clair College',
    'St. Francis Xavier University',
    'St. Mary\'s University',
    'St. Paul University',
    'St. Thomas University',
    'Thompson Rivers University',
    'Trent University',
    'Trinity Western University',
    'Télé-université, Université du Québec',
    'University Canada West',
    'University College of Cape Breton',
    'University College of Saint-Boniface',
    'University College of the Cariboo',
    'University College of the Fraser Valley',
    'University of Alberta',
    'University of British Columbia',
    'University of Calgary',
    'University of Guelph',
    'University of King\'s College',
    'University of Lethbridge',
    'University of Manitoba',
    'University of Moncton',
    'University of Moncton, Edmundston',
    'University of Moncton, Shippagan',
    'University of New Brunswick',
    'University of New Brunswick, Saint John',
    'University of Northern British Columbia',
    'University of Ontario Institute of Technology',
    'University of Ottawa',
    'University of Prince Edward Island',
    'University of Québec',
    'University of Regina',
    'University of Saskatchewan',
    'University of St. Jerome\'s College',
    'University of St. Michael\'s College',
    'University of Sudbury',
    'University of Toronto',
    'University of Toronto, Mississauga',
    'University of Toronto, Scarborough',
    'University of Trinity College',
    'University of Victoria',
    'University of Waterloo',
    'University of Western Ontario',
    'University of Windsor',
    'University of Winnipeg',
    'Université Laval',
    'Université de Montréal',
    'Université de Sherbrooke',
    'Université du Québec en Abitibi-Témiscamingue',
    'Université du Québec en Outaouais',
    'Université du Québec à Chicoutimi',
    'Université du Québec à Montréal',
    'Université du Québec à Rimouski',
    'Université du Québec à Trois-Rivières',
    'Vancouver Community College',
    'Victoria University Toronto, University of Toronto',
    'Wilfrid Laurier University',
    'William and Catherine Booth College',
    'York University',
    'Yukon College',
    'École Polytechnique de Montréal, Université de Montréal',
    'École de technologie supérieure, Université du Québec',
    'École des Hautes Études Commerciales',
    'École nationale d\'administration publique, Université du Québec'
];