name: Add Gitpod Link to Pull Request Comment

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  add-gitpod-link-to-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add Gitpod Link to Pull Request Comment
        uses: actions/github-script@v3.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            async function run() {
              const { owner, repo, number } = context.issue;

              // Generate Gitpod URL
              const gitpodURL = `https://gitpod.io/#https://github.com/${owner}/${repo}/pull/${number}`;

              // Create comment with Gitpod URL
              const { data: comment } = await github.issues.createComment({
                owner,
                repo,
                issue_number: number,
                body: `A Gitpod workspace for this pull request: ${gitpodURL}`
              });
            }

            run();
